name: SilverUtilities
main: com.flashbackmc.silverutilities.SilverUtilities
author: WhoIsJeb
version: 1.0-SNAPSHOT
commands:
  tellraw:
    description: Broadcasts exactly what is input.
    aliases: [tellr, tr]
    permission: silverutilities.tellraw
  fakeop:
    description: Totally ops player!
    permission: silverutilities.fakeop
  staffchat:
    description: Sends messages to the staff chat, or toggles it.
    aliases: [stch, sc]
    permission: silverutilities.staffchat.use
  discord:
    description: Provides the link to the server's discord.
    permission: silverutilities.discord
  colorcodes:
    description: Provides the link to the server's discord.
    aliases: [colourcodes, colors, colours]
    permission: silverutilities.colorcodes
permissions:
  silverutilities.player:
    description: Grants access to the plugin's basic commands.
    children:
      silverutilities.discord: true
      silverutilities.colorcodes: true
  silverutilities.staff:
    description: Grants access to the plugin's staff commands.
    children:
      silverutilities.tellraw: true
      silverutilities.fakeop: true
      silverutilities.staffchat.read: true
      silverutilities.staffchat.use: true
  silverutilities.tellraw:
    description: Grants access to /tellraw.
  silverutilities.fakeop:
    description: Grants access to /fakeop.
  silverutilities.discord:
    description: Grants access to /discord.
  silverutilities.colorcodes:
    description: Grants access to /colorcodes.
  silverutilities.staffchat.use:
    description: Grants access to /staffchat.
  silverutilities.staffchat.read:
    description: Grants the ability to read staff chat.